name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - swift:5.2-focal
          - swift:5.2-centos8
          - swift:5.3-focal
          - swift:5.3-centos8
          # see below for 5.4, 5.5, etc.
    container: ${{ matrix.image }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run tests
      run: swift test --enable-test-discovery
  # 5.4 is separate because there was a bug in the compiler that caused
  # us to need to run swift tets with the -sil-verify-none flag.
  linux-5_4:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - swift:5.4-focal
          - swift:5.4-centos8
    container: ${{ matrix.image }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run tests (without test discovery flag)
      run: swift test -Xswiftc -Xfrontend -Xswiftc -sil-verify-none
  linux-5_5-plus:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - swift:5.5-focal
          - swift:5.5-centos8
          - swift:5.6-focal
          - swift:5.7-focal
          - swift:5.7-jammy
          - swift:5.8-focal
          - swift:5.8-jammy
          - swift:5.9-focal
          - swift:5.9-jammy
          - swift:5.10-focal
          - swift:5.10-jammy
          - swift:6.0-focal
          - swift:6.0-jammy
          - swift:6.0-noble
          - swiftlang/swift:nightly-focal
          - swiftlang/swift:nightly-jammy
    container: ${{ matrix.image }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run tests
      run: swift test
  osx:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14
          - macos-15
    runs-on: ${{ matrix.os }}
    steps:
      - name: Select latest available Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run tests
        run: swift test --enable-test-discovery
